-- Create schema in H2 to match hardcoded entity schemas
CREATE SCHEMA IF NOT EXISTS "uat_ficoipb";
CREATE SCHEMA IF NOT EXISTS UAT_FICOIPB;
SET SCHEMA "uat_ficoipb";

CREATE TABLE ALUGUEL_ORIGEM
(
    ANOMES                    VARCHAR(6)                          NOT NULL,
    DEVICE_STATUS             VARCHAR(3) NULL,
    INSTITUTION_NUMBER        VARCHAR(8) NULL,
    MERCHANT_BOARDING_DATE    VARCHAR(8) NULL,
    MERCHANT_NUMBER           VARCHAR(20) NULL,
    SERVICE_CONTRACT_ID       VARCHAR(10) NULL,
    SIGNED_SALES_VALUE        DECIMAL(18, 2) NULL,
    TERMINAL_ID               VARCHAR(20) NULL,
    TERMINAL_INSTALATION_DATE VARCHAR(8) NULL,
    DESC_TERMINAL_TYPE        VARCHAR(100) NULL,
    VALOR_ORIGEM              DECIMAL(18, 2) NULL,
    REGIS_NUM                 VARCHAR(50) NULL,
    ID_CLI_TYPE               VARCHAR(3) NULL,
    FEE_CHARG_MODEL_CD        DECIMAL(3, 0) NULL,
    ID_PREPM                  VARCHAR(3) NULL,
    MCC                       VARCHAR(10) NULL,
    CAPTURE                   VARCHAR(10) NULL,
    ACTIVATION_DATE           VARCHAR(8) NULL,
    CNAE                      VARCHAR(10) NULL,
    GRUPO_ECONOMICO           VARCHAR(10) NULL,
    GRUPO_ECONOMICO_DESCRICAO VARCHAR(255) NULL,
    TERMINAL_TYPE             VARCHAR(10) NULL,
    ALIANCA                   VARCHAR(20) NULL,
    DT_INSERT_CONTROLE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ALUGUEL_EXCECAO
(
    ANOMES               VARCHAR(6)                          NOT NULL,
    INSTITUTION_NUMBER   VARCHAR(8)                          NOT NULL,
    MERCHANT_NUMBER      VARCHAR(20)                         NOT NULL,
    TERMINAL_ID          VARCHAR(20)                         NOT NULL,
    SERVICE_CONTRACT_ID  VARCHAR(10)                         NOT NULL,
    VALOR_EXCECAO        DECIMAL(18, 2)                      NOT NULL,
    DATA_LIMITE          DATE NULL,
    DT_INSERCAO_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ALUGUEL_PROCESSAMENTO_ALIANCA
(
    ANOMES                   VARCHAR(6)                          NOT NULL,
    INSTITUTION_NUMBER       VARCHAR(8)                          NOT NULL,
    MERCHANT_NUMBER          VARCHAR(20)                         NOT NULL,
    TERMINAL_ID              VARCHAR(20)                         NOT NULL,
    SERVICE_CONTRACT_ID      VARCHAR(10)                         NOT NULL,
    REGRA_APLICADA_DESCRICAO VARCHAR(255)                        NOT NULL,
    VALOR_ORIGEM             DECIMAL(18, 2)                      NOT NULL,
    VALOR_CORRIGIDO          DECIMAL(18, 2)                      NOT NULL,
    DT_INSERCAO_REGISTRO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE PRECO_JUSTO_SICREDI (
     ID                           NUMERIC(10,0)           NOT NULL,
     CNPJ                         VARCHAR(14),
     ANOMES                       VARCHAR(6),
     QUANTIDADE_ENQUADRAMENTO     NUMERIC(38,0),
     FLAG_ENQUADRAMENTO           NUMERIC(1,0),
     FLAG_COMUNICADO              NUMERIC(1,0),
     FLAG_MAJORADO                NUMERIC(1,0),
     DATAINCLUSAO                 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     FATURAMENTO_MEDIO_REALIZADO  NUMERIC(18,2),
     FATURAMENTO_COMBINADO        NUMERIC(18,2),
     FATURAMENTO_COMBINADO_MIN    NUMERIC(18,2),
     FATURAMENTO_COMBINADO_MAX    NUMERIC(18,2),
     FATURAMENTO_MAJORACAO_MIN    NUMERIC(18,2),
     FATURAMENTO_MAJORACAO_MAX    NUMERIC(18,2),
     DATA_BOARDING                VARCHAR(100),
     DATA_CREDENCIAMENTO          VARCHAR(100),
     FLAG_BASE_INCLUIDO           VARCHAR(100),
     DATA_BASE_INCLUIDOS          VARCHAR(100),
     DATA_BASE_EXCLUIDOS          VARCHAR(100),
     FATURAMENTO_PROMETIDO_ANUAL  NUMERIC(18,2),
     FLAG_BASE_EXCLUIDO           VARCHAR(100),
     FATURAMENTO_REALIZADO_M1     NUMERIC(18,2),
     FATURAMENTO_REALIZADO_M2     NUMERIC(18,2),
     FATURAMENTO_REALIZADO_M3     NUMERIC(18,2),
     REGRAS                       CLOB,
     RETURNCODE                   VARCHAR(3),
     SUCESSO                      VARCHAR(100),
     REGRA_APLICADA               VARCHAR(100),
     FATURAMENTO_PROMETIDO_MENSAL NUMERIC(18,2),
     SERVICE_CONTRACT             VARCHAR(3),
     INSTITUTION_NUMBER           VARCHAR(8),
     PRIMARY KEY (ID)
);

CREATE TABLE PRECO_JUSTO_SICREDI_ORIGEM_MERCHANT (
    ID                      NUMERIC(10,0)          NOT NULL,
    MERCHANT_NUMBER         VARCHAR(20),
    ANOMES                  VARCHAR(6),
    CNPJ                    VARCHAR(14),
    DATAINCLUSAO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_CREDENCIAMENTO     VARCHAR(10),
    FATURAMENTO_PROMETIDO   NUMERIC(18,2),
    DATA_BOARDING           VARCHAR(10),
    PRIMARY KEY (ID)
);

CREATE TABLE PRECO_JUSTO_SICREDI_ORIGEM_TERMINAL (
    ID                  NUMERIC(10,0)          NOT NULL,
    TERMINAL_ID         VARCHAR(20),
    TERMINAL_TYPE       VARCHAR(20),
    MERCHANT_NUMBER     VARCHAR(20),
    INSTITUTION_NUMBER  VARCHAR(8),
    SERVICE_CONTRACT    VARCHAR(3),
    ANOMES              VARCHAR(6),
    VALOR_ORIGEM        NUMERIC(18,2),
    DATAINCLUSAO        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CNPJ                VARCHAR(14),
    PRIMARY KEY (ID)
);
CREATE TABLE PRECO_JUSTO_SICREDI_TAXA_ALUGUEL (
    ID                        NUMERIC(10,0)         NOT NULL,
    INSTITUTION_NUMBER        VARCHAR(8),
    SERVICE_CONTRACT          VARCHAR(3),
    CNPJ                      VARCHAR(14),
    ANOMES                    VARCHAR(6),
    PRECO_JUSTO_SICREDI_ID    NUMERIC(10,0),
    VALOR_ALUGUEL_CALCULANDO  NUMERIC(10,2),
    TERMINAL_TYPE             VARCHAR(200),
    DATAINCLUSAO              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE PRECO_JUSTO_SICREDI_TAXA_ANTECIPACAO (
    ID                      NUMERIC(10,0)        NOT NULL,
    ANOMES                  VARCHAR(6),
    PRECO_JUSTO_SICREDI_ID  NUMERIC(10,0),
    AUTOMATICA              NUMERIC(1,0),
    DATAINCLUSAO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CNPJ                    VARCHAR(14),
    INSTITUTION_NUMBER      VARCHAR(8),
    SERVICE_CONTRACT        VARCHAR(3),
    EVENTUAL                NUMERIC(10,2),
    PRIMARY KEY (ID)
);

CREATE TABLE PRECO_JUSTO_SICREDI_TAXA_MDR (
    ID                        NUMERIC(10,0)         NOT NULL,
    ANOMES                    VARCHAR(6),
    PRECO_JUSTO_SICREDI_ID    NUMERIC(10,0),
    BANDEIRA                  VARCHAR(200),
    CREDITO                   NUMERIC(10,2),
    DEBITO                    NUMERIC(10,2),
    PARCELADOMAIOR6           NUMERIC(10,2),
    PARCELADOMENORIGUAL6      NUMERIC(10,2),
    DATAINCLUSAO              TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CNPJ                      VARCHAR(14),
    PRIMARY KEY (ID)
);


CREATE TABLE PRECO_JUSTO_SICREDI_ORIGEM_TAXAS_ANTECIPACAO (
    ID            NUMERIC(10,0)        NOT NULL,
    CNPJ          VARCHAR(14),
    ANOMES        VARCHAR(6),
    AUTOMATICA    NUMERIC(1,0),
    EVENTUAL      NUMERIC(18,2),
    DATAINCLUSAO  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

